sudo: required
services:
  - docker
before_install:
  - docker build -t cloud4saurav/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true cloud4saurav/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-207827953527"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWC_SECRET_KEY"